[package]
name = "screeps-starter-rust"
version = "0.0.0"
authors = []
edition = "2018"

[dependencies]
stdweb = "0.4"
log = "0.4"
fern = "0.5"
screeps-game-api = "0.7"
rls = "0.122.2"

[profile.release]
panic = "abort"
opt-level = "s"
lto = true
